### ISSUE TITLE
老哥 执行的时候出现了一些错误

### ISSUE THREAD

**Issue by xiaoleileier** [MisakaFxxk/MisakaF_Emby#2]
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "bot.py", line 73, in create
    check_groups = check_user_in_the_group(update,context)
  File "bot.py", line 242, in check_user_in_the_group
    check = context.bot.getChatMember(group_chat_id,user_id)
  File "/usr/local/lib/python3.6/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/telegram/bot.py", line 3379, in get_chat_member
    result = self._post('getChatMember', data, timeout=timeout, api_kwargs=api_kwargs)
  File "/usr/local/lib/python3.6/site-packages/telegram/bot.py", line 296, in _post
    f'{self.base_url}/{endpoint}', data=data, timeout=effective_timeout
  File "/usr/local/lib/python3.6/site-packages/telegram/utils/request.py", line 366, in post
    **urlopen_kwargs,
  File "/usr/local/lib/python3.6/site-packages/telegram/utils/request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Chat not found
但是排查不出来是那个地方触发的这个报错 
C7然后EMBY4.7.11

**Comment by MisakaFxxk** [comment]
telegram.error.BadRequest: Chat not found

报错：未找到群聊，检查第15行的group_chat_id填的对不对。如果不需要这个功能可以注释掉241-246行，然后添加一行：return 1
